plugin: amazon.aws.aws_ec2
regions:
  - ap-south-1

# Filter strictly for TaskFlow ECS worker nodes in running state
filters:
  tag:Role: ecs-host
  tag:Environment: prod
  instance-state-name: running

# Group instances logically based on tags
keyed_groups:
  - prefix: tag
    key: tags


# Use private IP addresses because instances reside in private subnets
compose:
  ansible_host: instance_id
  ansible_connection: "'community.aws.aws_ssm'"
  ansible_aws_ssm_region: "'ap-south-1'"
  ansible_aws_ssm_bucket_name: "'taskflow-prod-ssm-transfer-935710521571'"